console.log(evaluate('(* pi 56 72)'))
console.log(evaluate('(begin (* 86 76) (* 65 45) (define twice (lambda (x) (* 2 x) ) ))'))
console.log(evaluate('(twice 5)'))
console.log(evaluate('(/ 90 0)'))
console.log(evaluate('(+ 45 67 (+ 1 1))'))
console.log(evaluate('(define define 90)'))
console.log(evaluate('(define define 40)'))
console.log(evaluate('(+ define 40)'))
console.log(evaluate('define'))
console.log(evaluate('(define oops 50)'))
console.log(evaluate('( if (> 30 45) (+ 45 56) oops)'))
console.log(evaluate('(if (= 12 12) (+ 78 2) 90)'))
console.log(evaluate('(define circle_area ( lambda (r) (* pi r r)))'))
console.log(evaluate('(circle_area 3 )'))
console.log(evaluate('(define fact (lambda (n) (if (<= n 1) 1 (* n (fact (- n 1))))))'))
console.log(evaluate('(fact 3)'))
console.log(evaluate('(define twice (lambda (x) (* 2 x) ) )'))
console.log(evaluate('(twice 5)'))
console.log(evaluate('(define fib (lambda (n) (if (< n 2) 1 (+ (fib (- n 1) ) (fib (- n 2) )))))'))
console.log(evaluate('(fib 4)'))
console.log(evaluate('(sqrt 49 )'))
console.log(evaluate('(define triplet (lambda (x y z) (+ x (* y z) ) ) )'))
console.log(evaluate('(triplet (sqrt 49) 6 7)'))
console.log(evaluate('(define myfun (lambda (def parent) (* def parent)))'))
console.log(evaluate('(myfun 2 3)'))
console.log(evaluate('(define x 10)'))
console.log(evaluate('(define y x)'))
console.log(evaluate('y'))
console.log(evaluate('(define repeat (lambda (f) (lambda (x) (f (f x)))))'))
console.log(evaluate('((repeat twice) 10)'))


console.log(evaluater('(+ 1)'))
console.log(evaluater('(/ 40)'))
console.log(evaluater('(/ 40 400)'))
console.log(evaluater('(+ 1 3 4 6 8 9)'))
console.log(evaluater('(/ 10 12)'))
console.log(evaluater('(+ (+ 4 5) (- 16 4))'))
console.log(evaluater('(* pi 4 3)'))
console.log(evaluater('(+ 10 (sqrt 100))'))

console.log(evaluater('(begin (* 1 2) (* 3 7))'))
console.log(evaluater('(begin (begin (+ 1 2) (+ 3 7)))'))

console.log(evaluater('(begin (define r 10) (* pi (* r r)))'))
console.log(evaluater('(begin (define e 1) (+ e 3))'))
console.log(evaluater('(define plus +)'))
console.log(evaluater('(plus 10 20)'))

console.log(evaluater('(if (<= 3 7) 1 oops)'))
console.log(evaluater('(if (< 10 20) (+ 1 1) (+ 3 3))'))
console.log(evaluater('(if (< (* 11 11) 120) (* 7 6) oops)'))
console.log(evaluater('(+ (if (+ 1 1) 2 (+ 3 4)) 5)'))
console.log(evaluater('(if (> 4 3) (+ 1 1) (+ 5 5))'))
console.log(evaluater('(if (> 3 4) 5 7)'))
console.log(evaluater('(+ (if true 1 2) 5)'))
console.log(evaluater('(begin (begin (define x 12) (define y 1) (+ x y)))'))
console.log(evaluater('(begin (define x 12) (define y 1) (if (< x y) (+ (+ x y) (* x y)) (* x y)))'))
console.log(evaluater('(define define 10)'))
console.log(evaluater('(define define define)'))
console.log(evaluater('(define r 23)'))
console.log(evaluater('(+ r r)'))

console.log(evaluater('(define twice (lambda (x) (+ (* 2 x) (+ 2 x))))'))
console.log(evaluater('(twice 5)'))
console.log(evaluater('(define twice (lambda (x) (* 2 x)))'))
console.log(evaluater('(twice 5)'))

console.log(evaluater('(define circle-area (lambda (r) (* pi (* r r))))'))
console.log(evaluater('(circle-area 10)'))
console.log(evaluater('(define circle-area (lambda (r) (* pi (* r r))))'))
console.log(evaluater('(circle-area (* (+ 5 15) (- 14 10)))'))

console.log(evaluater('(define fact (lambda (n) (if (<= n 1) 1 (* n (fact (- n 1))))))'))
console.log(evaluater('(fact 3)'))
console.log(evaluater('(define fact (lambda (n) (if (<= n 1) 1 (* n (fact (- n 1))))))'))
console.log(evaluater('(fact (fact 3))'))