console.log(lispParser('(* pi 56 72)'))
console.log(lispParser('(begin (* 86 76) (* 65 45) (define twice (lambda (x) (* 2 x) ) ))'))
console.log(lispParser('(twice 5)'))
console.log(lispParser('(/ 90 0)'))
console.log(lispParser('(+ 45 67 (+ 1 1))'))
console.log(lispParser('(define define 90)'))
console.log(lispParser('(define define 40)'))
console.log(lispParser('(+ define 40)'))
console.log(lispParser('define'))
console.log(lispParser('(define oops 50)'))
console.log(lispParser('( if (> 30 45) (+ 45 56) oops)'))
console.log(lispParser('(if (= 12 12) (+ 78 2) 90)'))
console.log(lispParser('(define circle_area ( lambda (r) (* pi r r)))'))
console.log(lispParser('(circle_area 3 )'))
console.log(lispParser('(define fact (lambda (n) (if (<= n 1) 1 (* n (fact (- n 1))))))'))
console.log(lispParser('(fact 3)'))
console.log(lispParser('(define twice (lambda (x) (* 2 x) ) )'))
console.log(lispParser('(twice 5)'))
console.log(lispParser('(define fib (lambda (n) (if (< n 2) 1 (+ (fib (- n 1) ) (fib (- n 2) )))))'))
console.log(lispParser('(fib 4)'))
console.log(lispParser('(sqrt 49 )'))
console.log(lispParser('(define triplet (lambda (x y z) (+ x (* y z) ) ) )'))
console.log(lispParser('(triplet (sqrt 49) 6 7)'))
console.log(lispParser('(define myfun (lambda (def parent) (* def parent)))'))
console.log(lispParser('(myfun 2 3)'))
console.log(lispParser('(define x 10)'))
console.log(lispParser('(define y x)'))
console.log(lispParser('y'))
console.log(lispParser('(define repeat (lambda (f) (lambda (x) (f (f x)))))'))
console.log(lispParser('((repeat twice) 10)'))


console.log(lispParser('(+ 1)'))
console.log(lispParser('(/ 40)'))
console.log(lispParser('(/ 40 400)'))
console.log(lispParser('(+ 1 3 4 6 8 9)'))
console.log(lispParser('(/ 10 12)'))
console.log(lispParser('(+ (+ 4 5) (- 16 4))'))
console.log(lispParser('(* pi 4 3)'))
console.log(lispParser('(+ 10 (sqrt 100))'))

console.log(lispParser('(begin (* 1 2) (* 3 7))'))
console.log(lispParser('(begin (begin (+ 1 2) (+ 3 7)))'))

console.log(lispParser('(begin (define r 10) (* pi (* r r)))'))
console.log(lispParser('(begin (define e 1) (+ e 3))'))
console.log(lispParser('(define plus +)'))
console.log(lispParser('(plus 10 20)'))

console.log(lispParser('(if (<= 3 7) 1 oops)'))
console.log(lispParser('(if (< 10 20) (+ 1 1) (+ 3 3))'))
console.log(lispParser('(if (< (* 11 11) 120) (* 7 6) oops)'))
console.log(lispParser('(+ (if (+ 1 1) 2 (+ 3 4)) 5)'))
console.log(lispParser('(if (> 4 3) (+ 1 1) (+ 5 5))'))
console.log(lispParser('(if (> 3 4) 5 7)'))
console.log(lispParser('(+ (if true 1 2) 5)'))
console.log(lispParser('(begin (begin (define x 12) (define y 1) (+ x y)))'))
console.log(lispParser('(begin (define x 12) (define y 1) (if (< x y) (+ (+ x y) (* x y)) (* x y)))'))
console.log(lispParser('(define define 10)'))
console.log(lispParser('(define define define)'))
console.log(lispParser('(define r 23)'))
console.log(lispParser('(+ r r)'))

console.log(lispParser('(define twice (lambda (x) (+ (* 2 x) (+ 2 x))))'))
console.log(lispParser('(twice 5)'))
console.log(lispParser('(define twice (lambda (x) (* 2 x)))'))
console.log(lispParser('(twice 5)'))

console.log(lispParser('(define circle-area (lambda (r) (* pi (* r r))))'))
console.log(lispParser('(circle-area 10)'))
console.log(lispParser('(define circle-area (lambda (r) (* pi (* r r))))'))
console.log(lispParser('(circle-area (* (+ 5 15) (- 14 10)))'))

console.log(lispParser('(define fact (lambda (n) (if (<= n 1) 1 (* n (fact (- n 1))))))'))
console.log(lispParser('(fact 3)'))
console.log(lispParser('(define fact (lambda (n) (if (<= n 1) 1 (* n (fact (- n 1))))))'))
console.log(lispParser('(fact (fact 3))'))